### ISSUE TITLE
not able to setup cross-object communications: bug or code fault?

### ISSUE THREAD

**Issue by gamecubate** [maryrosecook/androjs#1]
I may be using androjs -- cool idea btw -- wrong.

Say a Planet object calls `andro.eventer(self).emit("rotate");` whenever it is told to rotate and I want another object, say Sky, to listen and act upon that.

Here's what I did:
1. Planet

```
var Planet = function() {
    var rotation = -90;

    this.rotate = function(){
        rotation += 1;
        andro.eventer(this).emit("rotate", rotation);
    };
}
```

2: Define sky-color behaviour:

```
var skyColorBehaviour = {
    setup: function(owner, eventer) {
        eventer.bind(this, "rotate", function() {
            console.log("got rotate message; will act upon that (TODO)");
        });
    }
};
```

3: Game

```
window.addEventListener('load', function() {
    var p = new Planet();

    var sky = new Sky();
    andro.augment(sky, skyColorBehaviour);

    // Launch
    function tick() {
        setTimeout(function(){
            requestAnimationFrame(tick);
            p.rotate();
        }, 1000);
    }
    tick();
});
```

Despite this, Sky s never receives the message that Planet p rotated. Nothing is shown in the console. 

I suspect I am using eventer.bind incorrectly.

Thanks in advance.
Alex

**Comment by maryrosecook** [comment]
Yes, I'm afraid inter-object communication is not supported.  In my own games, I do need this very occasionally.  I just hack it by doing something like: 

```
var Planet = function() {
    this.rotate = function(){
        andro.eventer(skyColorInstance).emit("planet-rotate", rotation);
    };
}
```

**Comment by gamecubate** [comment]
Thanks for the hint.
